#!/bin/bash

DIR="$(dirname "$0")"
. "${DIR}/config"

set -o errexit
set -o pipefail

IMAGE_URL=$(tkn tr describe --last -o jsonpath="{.status.taskResults[1].value}")
IMAGE_DIGEST=$(tkn tr describe --last -o jsonpath="{.status.taskResults[0].value}")

cat << EOF
  IMAGE_URL:    ${IMAGE_URL}
  IMAGE_DIGEST: ${IMAGE_DIGEST}
EOF

QUERY_URL="https://containeranalysis.googleapis.com/v1/projects/$PROJECT_ID/occurrences?filter=resourceUrl=\"${IMAGE_URL}@${IMAGE_DIGEST}\"%20AND%20kind=\"BUILD\""

MANIFEST_PATH=temp/manifest.json
curl -s -X GET -H "Content-Type: application/json" \
         -H "Authorization: Bearer $(gcloud auth print-access-token)" \
         $QUERY_URL > $MANIFEST_PATH

# Extract the signature.
SIG_PATH=temp/signature.sig
jq -r '.occurrences[0].envelope.signatures[0].sig' $MANIFEST_PATH | tr '\-_' '+/' | base64 -d > $SIG_PATH

# Verify the signature.
cosign verify-blob --key $KMS_URI --signature $SIG_PATH $SIG_PATH