apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: clone-scan-build-push
spec:
  description: | 
    This pipeline clones a git repo, scans code for vulnerabilities using 
    Snyc, builds a Docker image with Kaniko, and pushes it to a registry.
  params:
  - name: repo-url
    type: string
  - name: image-reference
    type: string
  workspaces:
  - name: shared-data
  tasks:
  - name: fetch-source
    taskRef:
      name: git-clone
    workspaces:
    - name: output
      workspace: shared-data
    params:
    - name: url
      value: $(params.repo-url)
  - name: scan-for-vulnerabilities
    taskRef:
      name: snyk-golang
    params:
    - name: args
      value:
      - --severity-threshold=medium
    runAfter:
    - fetch-source
    workspaces:
    - name: source
      workspace: shared-data
  - name: build-push
    runAfter:
    - fetch-source
    - scan-for-vulnerabilities
    taskRef:
      name: kaniko
    workspaces:
    - name: source
      workspace: shared-data
    params:
    - name: IMAGE
      value: $(params.image-reference)