apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: clone-scan-build-push
spec:
  description: | 
    This pipeline clones a git repo, scans code for vulnerabilities using 
    Snyc, builds a Docker image with Kaniko, and pushes it to a registry.
  params:
  - name: repo-url
    type: string
  workspaces:
  - name: shared-data
  tasks:
  - name: fetch-source
    taskRef:
      resolver: gcb-repo
      params:
      - name: repository
        value: projects/gcb-catalog-release/locations/us-central1/connections/github-conn/repositories/git-tkn
      - name: revision
        value: v0
      - name: pathInRepo
        value: task/git-clone/git-clone.yaml
      name: git-clone
    workspaces:
    - name: output
      workspace: shared-data
    params:
    - name: url
      value: $(params.repo-url)
